### ISSUE TITLE
Exception thrown after latest commit unknown property: kartik\widgets\ActiveForm::_defaultIconPrefix

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-activeform#103]
With your latest commit you have introduced an error in the ActiveForm

https://github.com/kartik-v/yii2-krajee-base/commit/df5741884e5715dbb03bb69a14a11ce034448693

    Setting unknown property: kartik\widgets\ActiveForm::_defaultIconPrefix
    in \vendor\kartik-v\yii2-krajee-base\src\BootstrapTrait.php at line 38 – yii\base\Component::__set('_defaultIconPrefix', 'glyphicon glyphicon-') 

because the ActiveForm class doesn't have this protected variable and is using the trait.

Perhaps it is better that to add the variable inside the trait itself?

btw also the `protected $_defaultBtnCss;` have the same issue.

**Comment by kartik-v** [comment]
The ActiveForm class already has these properties included to manage the change - [check here](https://github.com/kartik-v/yii2-widget-activeform/blob/master/src/ActiveForm.php). Both these changes to yii2-krajee-base and yii2-widget-activeform are on `dev-master` - so you may need to check if you have the latest dev-master versions of both extensions.

**Comment by Bhoft** [comment]
Ok my fault was that i have only `"kartik-v/yii2-widgets": "@dev"` in my composer.json. Guess this didn't get the dev version of the ActiveForm as well.
