### ISSUE TITLE
yii\base\ErrorException: kartik\form\ActiveForm and kartik\base\BootstrapTrait define the same property ($_isBs4)

### ISSUE THREAD

**Issue by bituze** [kartik-v/yii2-widget-activeform#104]
I am having this issue on server: 

`yii\base\ErrorException: kartik\form\ActiveForm and kartik\base\BootstrapTrait define the same property ($_isBs4) in the composition of kartik\form\ActiveForm. However, the definition differs and is considered incompatible. Class was composed in  vendor/kartik-v/yii2-widget-activeform/src/ActiveForm.php:47`

Can anyone help on what maybe cause of this incompatibility?

**Comment by pxao02** [comment]
Can confirm this issue for version 1.5.1. 
Issue is resolved by upgrading to latest dev-master. Will not update in composer unless "@dev" is specifically set.

**Comment by bituze** [comment]
The issue kept coming until i stopped using `kartik-v/yii2-widget-activeform` on that page

**Comment by kategee** [comment]
I'm having a similar issue, I get an error:

`Setting unknown property: kartik\form\ActiveForm::_isBs4`

**Comment by kartik-v** [comment]
Update your packages via composer to get latest dependencies to other extensions.
