### ISSUE TITLE
Before Update

### ISSUE THREAD

**Issue by AlessandroCuba** [kartik-v/yii2-widget-activeform#105]
I had today this error

`Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: kartik\form\ActiveForm::_isBs4' `

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/active-form)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-widget-activeform without other plugins.

**Comment by cahyasatya77** [comment]
same issue
