### ISSUE TITLE
Bootstrap4 implementation: not all classes compatible and architecture discussion

### ISSUE THREAD

**Issue by Enrica-r** [kartik-v/yii2-widget-activeform#106]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-activeform.
- [ ] This is not an usage question. I confirm having gone through and read the documentation for [ActiveForm](http://demos.krajee.com/widget-details/active-form) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue. --> code review
- [ ] I have included a failing test as a pull request (Optional).

Hello Kartik

Thank you very much for introducing BS4 in your controls.

I checked the code (1.52) what you have changed about BS4. There are some architectual inputs from my side.

First I have seen that ActiveForm / ActiveField isn't fully compatible. eg:
```php
$prefix = "col-{$size}-";
$this->_labelCss = $prefix . $span;
```
will not work anymore because BS4 has "sm, md, lg, xl" as size. BS3 "xs" is "col-12" because "xs" has been removed. It's just `col-12`. There are other changes like how to define horizontal forms. Further "xl" isn't in your size list. BS4 has enhancements like `.form-row`. see [Quackit tutorial with difference to BS3](https://www.quackit.com/bootstrap/bootstrap_4/tutorial/bootstrap_forms.cfm)

I like your generic approach with "BootstrapTrait" and eg. the function `getDefaultBtnCss()`. I wished you don't have a variable and function `ìsBs4` what assumes that we have Bs4 and other BS versions. It seems like BS3 "directly" distributed in the code of ActiveForm widget without naming it while BS4 modifies the class in if/endif closure. What will happen if BS5 will come? We will have code like `if (isBs4) {...} elseif (isBs5) {...} else {...}`.

I personally would prefer a css translation class in "yii2-krajee-base". This class loads a subclass depending on the defined BS version with its css class templates. ActiveField class and others call funtions like `getColClass(SIZE_TINY, 6);`. For BS3 the translater funtion returns "col-xs-6" and for BS4 "col-6". For responsive grids the function could support arrays also like `getColClass([SIZE_TINY, SIZE_SMALL, SIZE_XLARGE], [12,4,2]);`. This function returns for BS4 "col-12 col-sm-4 col-xl" and for BS3 "col-xs-12 col-sm-4, col-lg-2" (because lg doesn't exist). Theoretically with such a translator somebody could use Zurb Foundation also, then the function returns "columns small-12 large-2". With this centralized approach backward and foward compatibility could be ensured with help of additional css files and/or javascripts. (eg. new BS4 class "form-row" -> for BS3 returns "row")

Yii 3 developers want to make Yii core less dependant of external components like BS. Actually such a translater class with its definition should be part of packages "yii2-bootstrap" and "yii2-bootstrap4". Unfortunately Yii has the strategy to maintain all widgets per BS-version.

What do you think?

Rgds Enrica

**Comment by kartik-v** [comment]
@Enrica-r  thanks for your inputs - while I may not be able to answer all your points - here are few pointers:

1. The extensions architecture has been updated to ensure full backward compatibility with Bootstrap 3.x so that existing apps do not break.
2. With regards to `size` as you pointed out - Bootstrap4 has dropped support for `xs` size - but `lg` and `sm` will continue to work - in the end it is just for developers to include only the relevant size supported for the Bootstrap version they are using.
3. Currently `isBs4` is the easiest way to handle two different architectures for BS3 and BS4? Currently not thinking way ahead for any BS releases way far in future beyond BS4.x (whenever it comes) and not sure how that BS version will drastically change from BS4. Since it is unknown currently BS3 and BS4 support is on focus.

**Comment by Enrica-r** [comment]
@kartik-v  I understand your circumstances absolutely. I know it's extremely time consuming to have a perfect solution.

Optimal would be if your extension produces same result for BS3 and BS4. Concerning col size is your assumption not correct: BS hasn't dropped xs support. It's worse. xs is just col-12. But they have moved all breaking points, see:
- BS3: col-xs-*: <768px / sm: >=768px / md: >=992 / lg: >=1200  (see [BS3 tutorial](https://www.quackit.com/bootstrap/bootstrap_3/tutorial/bootstrap_grid_system.cfm)
- BS4: col-*: <576px / sm: >=576px / md: >=768px / lg: >=992 / xl: >=1200 (see [BS4 grid](https://getbootstrap.com/docs/4.0/layout/grid/#column-breaks)

This means a project migration to BS4 needs adaption of view defintion anyway. But ActiveForm needs to support 5 sizes.

**Comment by kartik-v** [comment]
Yes we could have a size mapping configuration - but I feel this is only needed for grid layouts from BS3 to BS4.

However for other sizing areas it must be left to the developer - e.g. there is no `btn-xs` in BS4 while `btn-lg` and `btn-sm` exists.

**Comment by kartik-v** [comment]
Refer kartik-v/yii2-krajee-base#100
