### ISSUE TITLE
Render a Checkbox with enclosed Label in BS3

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-activeform#111]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-activeform.
- [x] This is not an usage question. I confirm having gone through and read the documentation for [ActiveForm](http://demos.krajee.com/widget-details/active-form) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I have a Vertical ActiveForm where i render several fields but also a checkbox.
The label of the checkbox (for Form errors etc.) should be printed out the same way as other fields.

    $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_VERTICAL]);
     echo $form->field($review_model, 'signed_check')->checkbox(['name' => "SubmissionReview[signed_check]",'labelOptions'=>['style'=>'font-weight:bold; color:red; line-height:1.5em;']])->label('Signature Check');

With the earlier version of ActiveField version 1.4.9 the rendering was as expected.
With 1.5.4 (which is the version after i updated it) the additional Label isn't rendered.

## Expected behavior and actual behavior

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/1777147/45673150-3c54a180-bb2a-11e8-8d08-1deaa8b2fa41.png)

I was expecting...
![image](https://user-images.githubusercontent.com/1777147/45673114-25ae4a80-bb2a-11e8-8b30-60a049d88be6.png)

The problem is this line which disables the possibility to render a custom label for checkboxes as the offset is true.
https://github.com/kartik-v/yii2-widget-activeform/blob/460f13a55cb8952e6313bb9b24fee60b14d10158/src/ActiveField.php#L653-L655

**Comment by kartik-v** [comment]
Fixed via latest commit.

**Comment by DarthLegiON** [comment]
@kartik-v putting hidden input inside label (instead of outside it) causes problems with custom checkboxes in Internet Explorer / Edge browsers. Here is an example description:
https://www.triplet.fi/blog/problem-solved-custom-checkbox-not-working-on-edge/

I use Bootstrap Material checkboxes and also encountered this issue. Checkbox change just doesn't trigger when label clicked. There is three possible solutions: adding "for" to label, swap hidden input and checkbox and move hidden input back outside label (I don't know reasons to put it inside in one of the last updates).

**Comment by kartik-v** [comment]
Not sure of your issue. The `for` attribute is already being rendered for labels enclosing the checkbox/radio.

**Comment by Bhoft** [comment]
Hi,

today i updated yii2-widget-activeform to version 1.5.7
and sadly the problem is now even more worse.

The attribute Label Text isn't used as the checkbox label  and the custom label is not rendered any more (so the required label is missing).

![image](https://user-images.githubusercontent.com/1777147/47078795-5d311500-d204-11e8-8ed7-dbbccbb84b98.png)

Used the same php code as above.

Do you have an advice?

I have now troubles to downgrade because several other packages (kartik-v/yii2-detail-view) are depending ob kartik-v/yii2-builder which needs to be downgraded to get older versions of the kartik-v/yii2-widget-activeform.
