### ISSUE TITLE
For checkbox labels with 'label' option present, {beginLabel} and {endLabel} do not get rendered [$25]

### ISSUE THREAD

**Issue by nilsenpaul** [kartik-v/yii2-widget-activeform#112]
## Steps to reproduce the issue

1. Install Builder, use FormGrid
2. Set `bsVersion => '4.*',` in `config/params.php`
3. Create a checkbox with a label
```
 <?= FormGrid::widget([
           'model' => $profile,
           'form' => $form,
           'autoGenerateColumns' => true,
           'rows' => [
             [
                 'attributes' => [
                     'gdpr' => [
                         'type' => Form::INPUT_CHECKBOX,
                         'label' => $gdprRegister,
                     ],             
                 ],                 
             ],                     
         ]
     ]); 
 ?>
```
## Expected behavior and actual behavior
I expect a label to be shown correctly, within a label tag. What I see (see screenshot) is the label's title, without label tags, but with `{beginLabel}` and `{endLabel}` in it.
Checkboxes without a label option get rendered correctly.

![schermafbeelding 2018-09-17 om 15 34 48](https://user-images.githubusercontent.com/6794819/45817236-6353d480-bcde-11e8-8ba7-77ec05a4ed98.png)

**Comment by nilsenpaul** [comment]
Then I thought, just put the content in the model's `attributeLabels`, but that gets encoded by default by ActiveField.php, and it contains a link. So, I really need this label option.

**Comment by kartik-v** [comment]
Resolved via updated enhancement commit.
