### ISSUE TITLE
v1.5.3, different rendering of BS3 checkbox

### ISSUE THREAD

**Issue by craiglondon** [kartik-v/yii2-widget-activeform#113]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-activeform.
- [x] This is not an usage question. I confirm having gone through and read the documentation for [ActiveForm](http://demos.krajee.com/widget-details/active-form) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Updated from v1.4.9 to v1.5.3

## Expected behavior and actual behavior

"control-label" was added to the label rendered inside the checkbox div.

http://bootstrapdocs.com/v3.3.4/docs/css/#checkboxes-and-radios

control-label should not be used in this manner per the docs above

```
<div class="checkbox">
  <label>
    <input type="checkbox" value="">
    Option one is this and be sure to include why it's great
  </label>
</div>
<div class="checkbox disabled">
  <label>
    <input type="checkbox" value="" disabled>
    Option two is disabled
  </label>
</div>
```

From my actual code
Before
```
<div class="form-group field-payment-iscreateaccount">
    <div class="checkbox">
        <input type="hidden" name="Payment[isCreateAccount]" value="0">
        <label>
            <input type="checkbox" id="payment-iscreateaccount" name="Payment[isCreateAccount]" value="1"> Remember me with an account
        </label>
    </div>
    <div class="help-block"></div>
</div>
```

After
```
<div class="form-group highlight-addon field-payment-iscreateaccount">
    <div class="checkbox">
        <label class="control-label">
            <input type="hidden" name="Payment[isCreateAccount]" value="0">
            <input type="checkbox" id="payment-iscreateaccount" name="Payment[isCreateAccount]" value="1"> Remember me with an account
        </label>
        <div class="help-block"></div>
    </div>
</div>
```

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.2
- yii2-widget-activeform version: v1.5.3

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/active-form)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-activeform without other plugins.

**Comment by kartik-v** [comment]
Is there an issue with this CSS class getting added?

**Comment by craiglondon** [comment]
Thank you!

**Comment by craiglondon** [comment]
v1.5.3 looks good!

```
<div class="form-group highlight-addon field-payment-iscreateaccount">
    <div class="checkbox">
        <label>
            <input type="hidden" name="Payment[isCreateAccount]" value="0">
            <input type="checkbox" id="payment-iscreateaccount" name="Payment[isCreateAccount]" value="1"> Remember me with an account
        </label>
        <div class="help-block"></div>
    </div>
</div>```
