### ISSUE TITLE
Error: Undefined class constant 'BS_CONTROL_LABEL'

### ISSUE THREAD

**Issue by die-coding** [kartik-v/yii2-widget-activeform#114]
Error: Undefined class constant 'BS_CONTROL_LABEL' in ...\vendor\kartik-v\yii2-widget-activeform\src\ActiveField.php:1084
Stack trace:
#0 ...\vendor\kartik-v\yii2-widget-activeform\src\ActiveField.php(460): kartik\form\ActiveField->initActiveField()
#1 ...\vendor\yiisoft\yii2\base\BaseObject.php(109): kartik\form\ActiveField->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 ...\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 ...\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('kartik\\form\\Act...', Array, Array)
#5 ...\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('kartik\\form\\Act...', Array, Array)
#6 ...\vendor\yiisoft\yii2\widgets\ActiveForm.php(333): yii\BaseYii::createObject(Array)
#7 ...\modules\administrator\views\record-presensi\_tidak-masuk.php(38): yii\widgets\ActiveForm->field(Object(app\models\RecordPresensi), 'tanggal')
#8 ...\vendor\yiisoft\yii2\base\View.php(336): require('E:\\xampp\\htdocs...')
#9 ...\vendor\yiisoft\yii2\base\View.php(254): yii\base\View->renderPhpFile('E:\\xampp\\htdocs...', Array)
#10 ...\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('E:\\xampp\\htdocs...', Array, Object(app\modules\administrator\controllers\RecordPresensiController))
#11 ...\vendor\yiisoft\yii2\base\Controller.php(384): yii\base\View->render('_tidak-masuk', Array, Object(app\modules\administrator\controllers\RecordPresensiController))
#12 ...\modules\administrator\controllers\RecordPresensiController.php(81): yii\base\Controller->render('_tidak-masuk', Array)
#13 [internal function]: app\modules\administrator\controllers\RecordPresensiController->actionRombel('2018-09-26', NULL)
#14 ...\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#15 ...\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 ...\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('rombel', Array)
#17 ...\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('administrator/r...', Array)
#18 ...\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#19 ...\public\index.php(27): yii\base\Application->run()
#20 {main}

**Comment by kartik-v** [comment]
You need to ensure you have updated pacakages via composer and have updated dependencies. The issue is you folks have only partially updated yii2-widget-activeform but do not have the updated dependencies like yii2-nested-sets.

**Comment by schmunk42** [comment]
@kartik-v You should require krajee-base `>=1.9.7` here, I think - I got the same error with 1.9.6

**Comment by kartik-v** [comment]
Will check and incorporate in upcoming reelase. Not sure why you have version 1.9.6 of yii2-krajee-base though if you are auto updating via composer. The latest stable release is V1.9.7
