### ISSUE TITLE
Undefined class constant 'MOBILE_COUNTRY_CODE'

### ISSUE THREAD

**Issue by poovizhi796** [kartik-v/yii2-widget-activeform#124]
In Model page,
public function rules()
    {
        $rules = [
[[self::SMS_ACCOUNT_ID, self::SMS_AUTH_TOKEN, self::SMS_SENDER_ID,self::SMS_COUNTRY_CODE, self::MOBILE_COUNTRY_CODE], 'required'],
];
}

View Page:
<div class="col-md-6">
                        <?= $form->field($model, $model::MOBILE_COUNTRY_CODE)->textInput(['type' => 'number']); ?>
                    </div>

**Comment by kartik-v** [comment]
Sorry not related to this extension. Seems some coding issue at your end. Please use this repo to report only bugs/enhancements related to this extension.
