### ISSUE TITLE
[1.6.0] Hint blocks are help blocks

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-widget-activeform#131]
https://github.com/kartik-v/yii2-widget-activeform/blob/64b83af75b99e9f48cb65aee5288bedde9943b39/src/ActiveField.php#L504

Are you sure that this is correct? We just updated yii2-widget-activeform and under an **BS3** env (which uses `div` and  class`hint-block` as default) all changed into `p` with `help-block`.

**Comment by kartik-v** [comment]
The `help-block` class is the Bootstrap 3 CSS default - as implemented in [yii2-bootstrap base extension build as seen here](https://github.com/yiisoft/yii2-bootstrap/blob/caba7032f91acffdafb0f10dab150639803df667/src/ActiveField.php#L358).

However, will add the enhancement to get a standard `hint-block` class across BS versions.
