### ISSUE TITLE
ActiveForm.php still references bootstrap4 and there is no bootstrap5 equivalent

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-widget-activeform#132]
In ActiveForm.php, the following code exists:

```
$formCss = 'kv-form-bs3';
        if ($bsVer !== 3) {
            $formCss = 'kv-form-bs4';
            if ($this->tooltipStyleFeedback) {
                $css[] = 'tooltip-feedback';
            }
        }
```

It's checking for bootstrap3 and if that doesn't exist, default to bootstrap4.  There is no bootstrap5 code here.  

In `registerAssets()` there is code of `kvBs4InitForm()` but no bootstrap5 equivalent.

Reference #128

**Comment by kartik-v** [comment]
This is an expected logic which supports both bootstrap4 and bootstrap5. What is the issue you are facing?

**Comment by adamwinn** [comment]
I have a form element and the class associated with it is `class="row row-cols-lg-auto g-3 align-items-center form-inline kv-form-bs4"`.  I expected it to say `kv-form-bs5`, since I dont even have bootstrap4 installed

**Comment by kartik-v** [comment]
It will work with bootstrap 5 as well (as mentioned before the CSS class `kv-form-bs4` will work with both bootstrap 4 and bootstrap 5)
