### ISSUE TITLE
Error from version 1.6.0 with PHP 5.6

### ISSUE THREAD

**Issue by yuryeuceda** [kartik-v/yii2-widget-activeform#135]
Friend

I'm using PHP 5.6 and I update the active form widget with composer and I got 1.6.1 version and then I was having an error with ?? operator in file ActiveForm.php 
I did some research and I found that operator ?? doesn't exist in PHP 5.6. So I downgrade the version to 1.5.9 and it works like a charm. (BTW I can't upgrade PHP from 5.6 to 7 due to company policies)

The problem is lines 216 and 217 as shown in picture
![image](https://user-images.githubusercontent.com/19900241/154381094-4e31cfef-360e-4cd2-883f-7c29b0b94efd.png)

I would like if is possible to revert this change in order to keep compatibility with the widget for PHP 5.6 projects.

Thank you very much for your effort.

**Comment by kartik-v** [comment]
Noting an enhancement for backward compatibility - its difficult though for future... as Yii2 framework is moving to PHP 7.x and beyond.
