### ISSUE TITLE
Enhance ActiveForm to dynamically configure enabled, readonly and staticOnly flags

### ISSUE THREAD

**Issue by stovesy** [kartik-v/yii2-widget-activeform#136]
I wonder if you would consider the following enhancement.
It is an alteration to the  protected function initDisability(&$options) in ActiveField.php
The following will disable any attributes which are not active. I am using this to automatically disable unavailable fields as defined in scenarios.

$model = $this->model;
if (!in_array($this->attribute, $model->activeAttributes())) {
	$options['disabled'] = true;
}

Thanks for you time

**Comment by kartik-v** [comment]
This is developer specific (of overriding model methods which is not standard). So skipping this, because this can be achieved easily with the ActiveForm config for your use caseas below:

```php
use kartik\form\ActiveForm;

$form = ActiveForm::begin([
    'fieldConfig' => ['disabled' => $model->activeAttributes()]
]);
// render your active fields - all will use the default field config setting above.
ActiveForm::end();
```

**Comment by kartik-v** [comment]
Noting an enhancement - this may need additional settings at the form level.
