### ISSUE TITLE
disabled in ActiveField will always be overwritten, when diasabled is set in ActiveForm

### ISSUE THREAD

**Issue by HagnMarkus** [kartik-v/yii2-widget-activeform#139]
Version 1.6.3

When disabled is set (true or false) in ActiveForm it overwrites **always** disabled in ActiveField. So it is not possible to set a Field to disabled in an enabled Form.

Code in ActiveField:

```
/**
 * Parses the form flag (for disabled/readonly).
 *
 * @param  string  $flag
 * @param  array  $options
 * @return void
 */
protected function parseFormFlag($flag, &$options)
{
    if (!property_exists($this->form, $flag)) {
        return;
    }
    $action = $this->form->$flag;
    if ($action && is_callable($action)) {
        $options[$flag] = call_user_func_array($action, [$this->model, $this]);
    } else {
        $options[$flag] = $action;
    }
}
```

Code in 1.6.2

```
if ($this->form->disabled && !isset($options['disabled'])) {
    $options['disabled'] = true;
}
```

**Comment by kartik-v** [comment]
Have provided a fix. Kindly check and confirm if it resolves the issue and will tag a new release.

**Comment by HagnMarkus** [comment]
Now, when you set disabled = true for ActiveForm and disabled = false for ActiveField, it will enable the ActiveField in the disabled Form. Is this right and so wanted?

By the way: My problem is solved.

**Comment by kartik-v** [comment]
> Now, when you set disabled = true for ActiveForm and disabled = false for ActiveField, it will enable the ActiveField in the disabled Form. Is this right and so wanted?
> 
> By the way: My problem is solved.

No - with this fix, if the ActiveField `disabled` or `readonly` option is set (whether `true` or `false`),  it will override the ActiveForm setting. Is this not what you are seeing?

**Comment by kartik-v** [comment]
Have done further updates - please check if it works fine now.

**Comment by kartik-v** [comment]
> Now, when you set disabled = true for ActiveForm and disabled = false for ActiveField, it will enable the ActiveField in the disabled Form. Is this right and so wanted?
> 
> By the way: My problem is solved.

No - with this fix, if the ActiveField `disabled` or `readonly` option is set (whether `true` or `false`),  it will override the ActiveForm setting. Can you confirm if this works as intended?

**Comment by HagnMarkus** [comment]
Yes, for me it is fine now!

But the question was in general: Does it make sense to have an active field in a disabled form?
But this is more a matter of opinion. ;)

**Comment by kartik-v** [comment]
> Yes, for me it is fine now!
> 
> But the question was in general: Does it make sense to have an active field in a disabled form? But this is more a matter of opinion. ;)

It can help developers to program dynamic flags for `disabled` or `readonly` based on their use case... like having only a checkbox enabled (at ActiveField) while all other fields are disabled (in form) - or vice versa.

**Comment by HagnMarkus** [comment]
Thanks! I think you can tag a new release.
