### ISSUE TITLE
 Active Field disabled and readonly property not work 

### ISSUE THREAD

**Issue by t28hk** [kartik-v/yii2-widget-activeform#140]
**Disabled** and **readonly** property do not work when set
<?= $form->field($model, 'name')->textInput(['disabled'=>true,'readonly'=>true]) ?>
    
it seems in kartik\form\ActiveField

    public function textInput($options = [])
    {
        $this->initFieldOptions($options);
        Html::addCssClass($options, $this->addClass);
        $this->initDisability($options);

        return parent::textInput($options);
    }

    public function textarea($options = [])
    {
        $this->initFieldOptions($options);
        Html::addCssClass($options, $this->addClass);
        $this->initDisability($options);

        return parent::textarea($options);
    }
    
    public function dropDownList($items, $options = [])
    {
        $this->initDisability($options);
        $newBsCss = ($this->form->isBs(5) ? 'form' : 'custom').'-select';
        $class = $this->isCustomControl($options) ? $newBsCss : $this->addClass;
        Html::addCssClass($options, $class);

        return parent::dropDownList($items, $options);
    }
    
    
**initDisability($options)** this function do not need. I comment _$this->initDisability($options);_   it works.

**Comment by kartik-v** [comment]
Can you test with the latest dev-master version from the repo and confirm - there is a fix provided in #139.

**Comment by xlerr** [comment]
> Can you test with the latest dev-master version from the repo and confirm - there is a fix provided in #139.

Please release 1.6.4

**Comment by t28hk** [comment]
Yes, v1.6.4 has fixed this problem, it is ok now, thanks Kartik.
