### ISSUE TITLE
The help (error) block is not required for the static field type

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#23]
I believe the error block should be removed from the static field type since there's no interaction with the user and no entered data. Probably the hint block too.

EDIT: I found a scenario where the help blocks are required here. When a form displays a static field with invalid value (e.g. entered manually to the database but invalid in the model) and the form is submitted, the help block displays the validation error under the static field. If find this odd as I would expect that static fields are decoupled from the model and rendered as pure text so are no longer submitted back with the form inputs.

**Comment by kartik-v** [comment]
A static input is plain text markup. It cannot have any validation (its just plain text and not a form input). I am not sure about your use case and why you are updating database manually. In any case, if you need to display any markup above or below static input - its as similar to using an INPUT_RAW and rendering your own markup.

**Comment by kartik-v** [comment]
See #26

**Comment by YasserHassan** [comment]
Supposed you have a field like Job Title in an Employee's record form. You want the HR manager to be able to edit it while the employee can not, so you render that attribute for the HR manager as text input and to the employee as static. Now if that attribute was optional in the model (so null in some existing Employee records the database) and then later you changed the model and made it mandatory, when the employee submits the form (e.g. to change his home address), the job title validation error message will be displayed under the empty job title field.

Showing a validation error message under static text seems a little bit counter-intuitive, but then again during development this might be be useful, otherwise the form would seem unresponsive in such rare cases and nobody would know the problem. That's why I have mixed thoughts about it.

**Comment by YasserHassan** [comment]
#26 is good Kartik, the two options are available and it's up to the developer how to sue them.
