### ISSUE TITLE
Enhacement: Secondary value option for static-only form fields.

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#29]
I am suggesting an option to get the attribute value from a relation or function when the form is rendered in static mode, primarily to render the static version of drop down lists and multi-select combo boxes. It can be a field option called 'staticValue' as follows:
- A function/expression which could be used to display the values of multiple selections (e.g. convert them to a comma-separated list) or to format the value.
- Get the value from a relation. This can be used for single-selection like this:
```
'staticValue' => 'country->name'
// or 'staticValue' => '$model->country->name'
// Do not automatically use attribute ID because the relation name might be different.
// This gets the value form $model->country->name.
```
Along these lines, an option like 'staticFormat' too would be useful in certain cases.

**Comment by kartik-v** [comment]
Duplicate to #27 and also fix comment in kartik-v/yii2-builder#52. Fixed via #27.

No format is needed. The static value will not be assigned in quotes the way you have (as it will return a string)... instead it will be as simple as:
```php
'staticValue`=> $model->country->name
// or
'staticValue`=> Yii::$app->formatter->format($model->amount)->asDecimal()
```

**Comment by YasserHassan** [comment]
Your implementation is the straightforward way of doing it but to make sure all ideas are brought to the table, I meant to use a string for overall performance as this would avoid executing code in the interactive (non-static) form mode and delegate it somewhere else to be executed only in the static mode. For example you could avoid generating a related keywords list required to replace a multi-select combo box in the static mode each time the form is rendered as interactive. Also the relations could be evaluated there and null relations detected there.

**Comment by kartik-v** [comment]
You could always setup `staticValue` based on a condition when it is to be shown. Note that this value is not only to be displayed when form `staticOnly` property is set - but also when you are using a static input in a norma form.

```php
$form = ActiveForm::begin(['staticOnly' => $flag]);
echo $form->field($model, 'field', ['staticValue' =>$flag ? 'Value 1' : null]);
ActiveForm::end();
```

I want to keep it simple and straightforward at this stage and look at this working easily for all development scenarios (for developers to code this their own way using advanced functions). Parsing a string to a PHP code is always undesired - and will have performance/security issues to consider in a different way.

**Comment by kartik-v** [comment]
You could always setup `staticValue` based on a condition when it is to be shown and avoid code being executed when not needed. Note that this property is used NOT ONLY for static forms (where `staticOnly` property is set) - but also can be applied to a static input in a NORMAL form. An example in STATIC form:

```php
$form = ActiveForm::begin(['staticOnly' => $flag]);
// where you need
echo $form->field($model, 'field1', $flag ? ['staticValue'=>$model->relation->name] : [])->dropdownList($opts);
// where you don't need - staticValue is autoderived
echo $form->field($model, 'field2')
ActiveForm::end();
```

I want to keep it simple and straightforward at this stage and look at this working easily for all development scenarios (for developers to code this their own way using advanced functions). Parsing a string to a PHP code is always undesired - other than it being restricted to what you can achieve, it will also have performance/security issues to consider in a different way.

> **NOTE:** If you use **FormBuilder** from kartik-v/yii2-builder, you can easily setup your form and attribute configuration array based on the `flag` in the example above.

**Comment by YasserHassan** [comment]
I agree with you on the peace of mind and safety brought by the current implementation. It's a tradeoff and if I have to choose one only, it would be your approach.

But why is 'staticValue' used for static inputs in interactive forms? It would double the use of 'value' and might be confusing. I believe it's better to use staticValue in static forms only to override 'value' if exists while ignore it in interactive ones.

**Comment by kartik-v** [comment]
Static value is also been extended for normal forms - in case you wish to show a different value than the generated attribute value for some reason (specific to a use case).

**Comment by kartik-v** [comment]
Static value is also been extended for normal forms - in case you wish to show a different value than the generated attribute value for some reason (specific to a use case). The only thing with static input is that it generates the markup of label, field, hint, and error - you can use it to your own advantage.

**Comment by kartik-v** [comment]
A classic use case for `staticValue` is to display some text when the field value is null.

**Comment by YasserHassan** [comment]
>Static value is also been extended for normal forms - in case you wish to show a different value than the generated attribute value for some reason

Are you referring to 'staticValue? If so, isn't 'value' enough for this?
>A classic use case for staticValue is to display some text when the field value is null.

This could be confusing, my opinion is that a dedicated option like 'nullValue' (for nulls) or 'emptyValue' (for nulls and empty strings) would be better.

**Comment by kartik-v** [comment]
There is no value property for static inputs... its not a form input in the first place (its just a HTML markup).

**Comment by YasserHassan** [comment]
Got it. I shall wait for the documentation update to clarify these scenarios before further comments if any.
