### ISSUE TITLE
checkbox issue

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-activeform#31]
I"m trying to display a check on a checkbox according to a value from I:m reading from a DB.
Unfortunately the chackbox is not being displayed as checked.
What I"m doing wrong (the if statement is working correctly)?

if ($dishType == 10) // check the check box
{
          echo $form->field($model, 'menuActive')->checkbox(['name'=>'checkID_' . $dishType, 
                   'checked' => true, 'label' =>'Active?']);
}
else // leave the checkbox unchecked
	echo $form->field($model, 'menuActive')->checkbox(['name'=>'checkID_' . $dishType, 
                 'checked'=>0, 'label' =>'Active?']);

**Comment by kartik-v** [comment]
Set the model attribute value directly this way... 

```php
if ($dishType == 10) // check the check box
{
   $model->menuActive = true;
} else {
   $model->menuActive = false;
}
```
