### ISSUE TITLE
autoPlaceholder and tabular input

### ISSUE THREAD

**Issue by embambols** [kartik-v/yii2-widget-activeform#33]
In case tabular input is used (following this tutorial: http://www.yiiframework.com/doc-2.0/guide-input-tabular-input.html):
```
foreach ($settings as $index => $setting) {
    echo $form->field($setting, "[$index]value")->label($setting->name);
}
```
then autoPlaceholder sets placeholder="[1]value"

It would be nice if you could override placeholder value when using autoPlaceholder with something. Either using that label() from tutorial

$form->field($setting, "[$index]value")->**label('anything');**
or
$form->field($setting, "[$index]value")->textInput([**'placeholder' => 'anything'**]);

Maybe it already can be done and I'm missing something?

**Comment by kartik-v** [comment]
You can check now. It should be resolved with this fix.

**Comment by embambols** [comment]
Works! That was fast. Thanks
