### ISSUE TITLE
Unaligned labels for Checkboxes and Radio Buttons with enclosedByLabel = false in horizontal forms

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#35]
Checkboxes and radio buttons with enclosedByLabel = false in horizontal forms appear lower than their labels as shown here:
![checbox_radio_bug](https://cloud.githubusercontent.com/assets/9349772/6843123/5683ca9e-d3a8-11e4-807c-37ec2fd3263b.png)

**Comment by kartik-v** [comment]
Fixed via #36
