### ISSUE TITLE
SCREEN_READER labels occupy space in horizontal forms

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#37]
In horizontal forms with fields having `'showLabels' => ActiveForm::SCREEN_READER`, the generated fields are expected to occupy the full width of their containers the same as with showLabels = false. Instead, the label location remains vacant as shown below. When the browser width is decreased so the form is displayed as vertical, this space moves above the field creating extra space between it and the field above.
![4](https://cloud.githubusercontent.com/assets/9349772/6847407/2f81f73c-d3cf-11e4-8cbf-ea872c6ed07b.png)

**Comment by kartik-v** [comment]
No its intended that you must need to set `showLabels` to `false` to set the input to span the full width for horizontal forms.

The  `showLabels` property when set to SCREEN_READER will be available on screen readers for accessibility.

**Comment by kartik-v** [comment]
Will figure out this later.

**Comment by YasserHassan** [comment]
The `.sr-only` class alone is sufficient for accessibility. It is intended for use in situations where the label needs to be removed while preserving accessibility. So to fulfill both needs, `.sr-only` renders the label as if non-existing visually while actually keeping it in the HTML for screen readers. In other words, no-label and `.sr-only` label should both act the same from a visual standpoint. With this logic, it's more intuitive that `SCREEN_READER` fields act the same as setting `showLabels` to `false` but without the need to use `showLabels`.

**Comment by YasserHassan** [comment]
@kartik-v I was already working on it but you beat me to it :) There's still a fix required. Now the generated field has full span while the label span still exists. This creates a small extra space above the field different from the normal spacing. To fix this, the label span need to be totally removed.

**Comment by kartik-v** [comment]
You can check now.

**Comment by YasserHassan** [comment]
You beat me again. Yes now fixed. Thank you.

**Comment by YasserHassan** [comment]
Seems there's a side effect. In inline forms, setting showLabels to either true or false totally removes the label from the HTML while setting it to SCREEN_READER is OK.

**Comment by YasserHassan** [comment]
Created a new issue #38 for the last note above.
