### ISSUE TITLE
New repository for documentation and examples

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#45]
This request is for all extensions. It would be good to have a separate repository for the documentation including the working examples shown in the website. This way it can be available for offline use as a backup measure, and contributions can be made to the documentation too besides the code.

**Comment by kartik-v** [comment]
The docs and demos page already exist at http://demos.krajee.com.

At this stage will not have time to do additional docs beyond them. Feel free to contribute or enhance to this.

Closing this - unless you find a better option or suggestion to revive this.

**Comment by YasserHassan** [comment]
@kartik-v yes I have a suggestion. I am not suggesting that you do additional docs (you have done a huge job already). As far as I know Yii2's online documentation is automatically generated from a GitHub documentation repository. I am suggesting that you publish the source of the website/docs/examples at http://demos.krajee.com as-is to a separate repository and establish that auto-generate process (I'd like to help here). From that time on, any modifications required for the docs or examples would be done to the repo instead. This way followers can get notified when the documentation is updated and can also contribute to them with enhancement and probably more examples. If there's a database used, it could be added to the repo as an initial migration/SQL script then following changes as migrations run on both the website database and offline by developers if/when required.
