### ISSUE TITLE
Bootstrap input group addons for horizontal forms

### ISSUE THREAD

**Issue by arash26** [kartik-v/yii2-widget-activeform#46]
After last update I've problem on prepend addon
![form](https://cloud.githubusercontent.com/assets/1711136/7101014/ce1a9f56-e055-11e4-948a-e2f518e7efc3.png)

**Comment by kartik-v** [comment]
Can you check if any of your other CSS or other themes which may be overriding this.

The [prepend addon works fine on the demos](http://demos.krajee.com/widget-details/active-field#prepend-addon).

**Comment by kartik-v** [comment]
OK I see you have a horizontal form... will update.

**Comment by kartik-v** [comment]
You can check now.

**Comment by arash26** [comment]
Thanks,
I changed my form to Vertical

**Comment by kartik-v** [comment]
No problems. You can use horizontal form if you want to as well.
