### ISSUE TITLE
Setting unknown property: kartik\form\ActiveField::skipFormLayout

### ISSUE THREAD

**Issue by RamzyVirani** [kartik-v/yii2-widget-activeform#47]
Hi kartik, I am getting subjected error when trying to use sub attributes with FormGrid, 
I tried to check it by myself, and I found out that all files are updated (v1.4.1) but ActiveField.php still has v 1.3.0, I tried to execute `composer update` several times and `composer require kartik-v/yii2-widget-activeform "*"` but ActiveField.php is not getting updated. Can you please guide me what m I doing wrong here.

I also tried to clear cache of composer by `composer clearcache` but still ActiveField.php is not getting update.

Thanks in advance

**Comment by kartik-v** [comment]
This could be due to corrupted composer packages on your install.

[Follow this webtip](http://webtips.krajee.com/composer-fails-update-vendor-packages/) to re-install your packages via composer

**Comment by RamzyVirani** [comment]
no luck, I renamed vendor directory and composer.lock file, I also cleared cache of composer but its not getting the latest version of ActiveField.php

**Comment by kartik-v** [comment]
You need to check your composer settings. Try setting minimum-stability to `dev` in your application root's composer.json or follow this [web-tip](http://webtips.krajee.com/setting-composer-minimum-stability-application/) if you wish to use minimum-stability as `stable`.

**Comment by RamzyVirani** [comment]
Thank you kartik, I updated the composer.json entry from 
`"kartik-v/yii2-widget-activeform": "*"`
to
`"kartik-v/yii2-widget-activeform": "@dev"`
and now its working like a charm.
