### ISSUE TITLE
ActiveField disables hints prematurely.

### ISSUE THREAD

**Issue by SamMousa** [kartik-v/yii2-widget-activeform#49]
During initialization ActiveField checks if $this->parts['{hint}'] is set and if not it sets showHints to false.
When used with a form widget the hint is set after initialization, but it is not displayed since showHints was set to false.

**Comment by kartik-v** [comment]
Not sure if I understand or if your expectation is correct.

If you have set `showHints` to false at form level -- all hints will be entirely disabled for the entire form, the same is with `showLabels` or `showErrors` as well.

**Comment by SamMousa** [comment]
This is a snippet from line 816 in ActiveField.php:

        $showHints = $this->getConfigParam('showHints');
        if (!isset($this->parts['{hint}'])) {
            $showHints = false;
        }

This than passes the $showHints to mergeSettings where it then saves the value in _settings. 
Note that this is inside ActiveField and overrides any global settings regardless of the initial value.

However if later I call $field->hint("test") it will set the hint value, but $showHints is still saved in _settings.
So the hint is not displayed.

**Comment by kartik-v** [comment]
Ok - I get it.... hints are not rendered by default in yii core ... will update...

**Comment by SamMousa** [comment]
I am not sure if the error is in core but if you know what I mean it's all good =)

**Comment by kartik-v** [comment]
What I meant is the markup for error container are by default displayed in yii core as well as label... but not for hints... so it needs a slightly different treatment for handling its display.

**Comment by kartik-v** [comment]
Anyway - `kartik\form\ActiveField` class will need further enhancement due to [one of my proposed enhancements to attributeHints](https://github.com/yiisoft/yii2/issues/1468) that has been included in yii core by yii dev team...
