### ISSUE TITLE
Error after update 299b0f2 (Calling unknown method: ....getAttributeHint())

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-widget-activeform#51]
The error seems to be resulting from line 682 in file ActiveField.php.

While at it, I'm thinking aloud about the new render() function in the same file. The if statement
`if ($this->getConfigParam('showHints') === false)`
come before `if ($this->form->staticOnly === true)`
Wouldn't it be more optimized to check for staticOnly and returning if true first before processing regular form fields?

**Comment by kartik-v** [comment]
Read the CHANGE log to understand the updates. This is related to #50 & #49 and due to an upgrade in yii core. You need to ensure you have updated yii packages.

**Comment by YasserHassan** [comment]
@kartik-v great you are keeping up with Yii's pre-release progress. I was under the impression that you base your modifications on Yii's release versions only. I'll switch to Yii's master. If there's any way around this without losing your latest enhancements please let me know.
