### ISSUE TITLE
maxlength for activeField

### ISSUE THREAD

**Issue by vsmelarkod** [kartik-v/yii2-widget-activeform#52]
Hi Kartik,

How to add the maxlength attribute to an input field. ex: the following one doesnt work

echo $form->field($model, 'email', [
        'addon' => ['prepend' => ['content' => '@']],
        'options' => ['maxlength'=>127, 'placeholder' => 'Enter a valid email...'],
    ]);

**Comment by kartik-v** [comment]
Refer yii docs... you can try something like this below:

```php
echo $form->field($model, 'email', ['addon' => ['prepend' => ['content' => '@']]])
    ->textInput(['maxlength'=>127, 'placeholder' => 'Enter a valid email...'])
]);
```
