### ISSUE TITLE
Issue: Cannot control size of fields

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/yii2-widget-activeform#53]
I've been unable to found any option that provide size control of field. I checked in your classes, it seems to me used with full span property of active form.

$errorDivClass = "col-{$size}-{$this->form->fullSpan}";
$inputDivClass = $errorDivClass;

is there anyway that I add class to active field and it behaves accordingly?

Like this:

<?= $form->field($model, 'att', ['inputDivClass' => 'col-lg-5'])->dropDownList($jsonArr); ?>

This is my form tag:

<?php $form = ActiveForm::begin([
        'id' => 'question-create',
        'type' => ActiveForm::TYPE_HORIZONTAL,
        'formConfig' => ['labelSpan' => 3, 'deviceSize' => ActiveForm::SIZE_SMALL]
    ]); ?>

**Comment by kartik-v** [comment]
Yes this is the way it should work - need to check if the size is not being passed properly... will update.
