### ISSUE TITLE
Hint container

### ISSUE THREAD

**Issue by razzzo** [kartik-v/yii2-widget-activeform#57]
Hey,

Is there any specific reason for omitting {hint} tag in [buildTemplate()] (https://github.com/kartik-v/yii2-widget-activeform/blob/master/ActiveField.php#L901) method?

```buildLayoutParts()``` and then ```setLayoutContainer('hint', $errorDivClass);```
prepares container for hint as follows (or similar)
```html
<div class=\'col-md-offset-2 col-md-6\'>{hint}</div>
```
but it is not applied and I'm getting something like 
![hint_1](https://cloud.githubusercontent.com/assets/6398977/8624384/c883b626-2737-11e5-855d-bb54877e4afc.png)

After small update in ActiveField::buildTemplate() 
```php
protected function buildTemplate()
    {
        ...
        $this->template = strtr($this->template, [
            '{label}' => $showLabels ? "{$this->contentBeforeLabel}{label}{$this->contentAfterLabel}" : '',
            '{input}' => str_replace(
                '{input}',
                $this->contentBeforeInput . $this->generateAddon() . $this->renderFeedbackIcon() . $this->contentAfterInput,
                $input
            ),
            '{error}' => $showErrors ? str_replace(
                '{error}',
                "{$this->contentBeforeError}{error}{$this->contentAfterError}",
                $error
            ) : '',
            // UPDATE
            '{hint}' => str_replace('{hint}', "{hint}", $hint)
        ]);
    }
```
I'm getting hint with applied container
![hint_2](https://cloud.githubusercontent.com/assets/6398977/8624557/02306c9c-2739-11e5-9730-378ef01fe68b.png)

I use ```ActiveForm::TYPE_HORIZONTAL``` form

**Comment by kartik-v** [comment]
Will need to check. This was changed a bit in #22 for an update in core yii active field rendering active hints differently.

Will check and update.

**Comment by razzzo** [comment]
Ok, thanks.

**Comment by kartik-v** [comment]
I cannot reproduce this... it seems to render fine. 

Ensure you have the latest updated version / release of the extension.

**Comment by razzzo** [comment]
You're right, it's fine.
I use ```class ActiveField extends \kartik\form\ActiveField```.
I did some modifications in my ```ActiveField::render()``` and that was the problem.

**Comment by kartik-v** [comment]
Yes if you are extending classes... please check with core extension inbuilt classes before reporting issues.
