### ISSUE TITLE
Problem when trying to Update to Ver. 1.4.4

### ISSUE THREAD

**Issue by iceyisaak** [kartik-v/yii2-widget-activeform#58]
I was using outdated version, so I tried to update to ver. 1.4.4 via composer.  However, composer kept installing Ver. 1.4.2 over and over.

So I ended up downloading a ZIP file to install it myself.  I'm not sure whether there was a problem with my composer or something else.

I'm a newbie by the way, and I'll be glad if you let me know what the problem actually is. :)

Cheers,
Isaak

**Comment by freezy-sk** [comment]
@iceyisaak which command have you used to update? `composer install` or `composer update`?

**Comment by kartik-v** [comment]
Latest release is 1.4.5
