### ISSUE TITLE
Unable to set "asButtonGroup" from radioList()

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-widget-activeform#60]
[radioList()](https://github.com/kartik-v/yii2-widget-activeform/blob/master/ActiveField.php#L624) has no way to set the [asButtonGroup](https://github.com/kartik-v/yii2-widget-activeform/blob/master/ActiveField.php#L664) parameter used in *getToggleFieldList()*.

This is a particular problem when using the Form Builder, where it is not possible to turn the radio list into a [bootstrap toggle button group](http://getbootstrap.com/javascript/#buttons).

**Comment by kartik-v** [comment]
You need to instead directly use the `radioButtonGroup` and `checkboxButtonGroup` within `kartik\form\ActiveField`... will add these constants to FORM Builder.

**Comment by kartik-v** [comment]
Resolved via kartik-v/yii2-builder#95
