### ISSUE TITLE
Idea: ActiveForm 'form' or 'content' option

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-widget-activeform#63]
Why not add a simple 'form' attribute that takes a ```kartik\builder\Form``` type and renders it between ```begin()``` and ```end()``` so that we can render both the ActiveForm and Form in one go like this:

```php
<?= \kartik\widgets\ActiveForm::widget([
	'form' => new \kartik\builder\Form([
		'model' => $model,
		'columns' => 12,
		'attributes' => [
			...
		],
	]),
]) ?>
```

Or taking it one step further and passing a configuration array to use the form builder, like this:

```php
<?= \kartik\widgets\ActiveForm::widget([
	'form' => [
		'model' => $model,
		'columns' => 12,
		'attributes' => [
			...
		],
	],
]) ?>
```

Or adding a simple but universal 'content' option that does nothing else but *echo* whatever is passed to it at the start of ```run()``` (after ```begin()```), as so:

```php
<?= \kartik\widgets\ActiveForm::widget([
	'content' => new \kartik\builder\Form::widget([
		'model' => $model,
		'columns' => 12,
		'attributes' => [
			...
		],
	]),
]) ?>
```

Either of the above three options would be enormously helpful.

**Comment by kartik-v** [comment]
The functionality can rather be achieved conversely and directly via [Form builder](http://demos.krajee.com/builder-details/form) and [FormGrid builder](http://demos.krajee.com/builder-details/form-grid) where all you need is to pass the ActiveForm instance to those widget components.

**Comment by vercotux** [comment]
You mean like this?

```php
<?= Form::widget([
	'form'			=> new \kartik\widgets\ActiveForm([
		'id'				=> 'form-test',
		'action'			=> ['/site/test'],
		'validateOnBlur'	=> false,
	]),
	'model'			=> $model,
	'columns'		=> 12,
	'attributes'	=> [
		...
	],
]); ?>
```

I've done a quick test and it seems to be working. Creating an instance of ```ActiveForm``` (with ```new```) shouldn't generate any code at that spot right? Meaning I would be able to store the whole ```Form``` as a variable?

**Comment by kartik-v** [comment]
For advanced cases where you need complex layouts you need to wrap it in between an ActiveForm begin and end. Refer the Form builder and FormGrid builder examples.

```php
use kartik\widgets\ActiveForm;
use kartik\builder\Form
$form = ActiveForm::begin([
    'id'                => 'form-test',
    'action'            => ['/site/test'],
    'validateOnBlur'    => false,
]);
echo Form::widget([
    'form' => $form,
    // other settings
]);

// another layout or config
echo Form::widget([
    'form' => $form,
    // other settings
]);

ActiveForm::end();
```
