### ISSUE TITLE
Enhancement to display and style hints via icon popups or label hover

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-activeform#64]
Refer kartik-v/yii2-widgets#283

**Comment by kurniawantaari** [comment]
Hi kartik, I'm looking in your documentation and example code, but I don't see how to use hint as a question mark or label hover. Could you help me? Thanks for your marvelous work!

**Comment by kartik-v** [comment]
Refer the [docs and demos for hints](http://demos.krajee.com/widget-details/active-field#input-hints)

**Comment by kurniawantaari** [comment]
Thanks! :D
