### ISSUE TITLE
Hint issue

### ISSUE THREAD

**Issue by seiweb** [kartik-v/yii2-widget-activeform#72]
Hello!
I have 2 forms:
```php
<?php
$form = ActiveForm::begin();
$form->field($model, 'subway_station',[
        'hintType' => ActiveField::HINT_SPECIAL,
        'hintSettings' => [
            'showIcon' => true,
            //'title' => '<i class="glyphicon glyphicon-info-sign"></i> Note'
        ]
    ])->hint('subway_station hint')
ActiveForm::end();
?>
...
<!-- <div class="nav-tab2"> -->
    <form style="display: none;">
        <input type="button" value="firstform">
    </form>

```
Hint not displayed.

**Comment by Enrica-r** [comment]
Please try with newest version 1.4.9 if it works now. I changed the container (divs instead of a table) because the Icon beside input didn't work. Otherwise I'm not sure what could be the issue.

**Comment by kartik-v** [comment]
@Enrica-r  the table markup has been retained - else the full-width styling is not achievable...

**Comment by kartik-v** [comment]
@Enrica-r  the table markup has been retained - else the full-width styling is not achievable...

@seiweb check if you do not have javascript errors on your page and that the bootstrap js is properly loaded for BS popover to work. You can cross [check with the docs and demos](http://demos.krajee.com/widget-details/active-field#input-hints).

**Comment by mattheobjornson** [comment]
I've met the same issue with 2 forms in one view (in 1.4.9 as well). Problem is that the default container is "form", so the selector does not work properly with multiple forms on page.
Manually setting container to form id solves the issue for me. 
```
        'hintSettings' => [
            'container' => '#registration-form'
        ]
```

**Comment by wfcreations** [comment]
I have some issue with label, when I try disable hover and click event in label, this condition make the icon invisible (probabily It's not necessary this check):

($this->getHintData('onLabelClick') || $this->getHintData('onLabelHover'))

Because I want events only in icon

* I had the same problem reported in this thread, I solved making container be false

**Comment by kartik-v** [comment]
Enhanced via 3f550c7.
