### ISSUE TITLE
ActiverField hint icon not works without enabling label hover/click 

### ISSUE THREAD

**Issue by nrob81** [kartik-v/yii2-widget-activeform#84]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not an usage question. I confirm having gone through and read the documentation for [ActiveForm](http://demos.krajee.com/widget-details/active-form) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [x] The issue still exists against the latest `master` branch of yii2-widget-activeform.
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. create an activefield with icon enabled and label click/hover disabled
echo $form->field($model, 'r1', [
    'hintType' => ActiveField::HINT_SPECIAL,
    'hintSettings' => [
        'onLabelClick' => false,
        'onLabelHover' => false,
        'onIconClick' => true,
        'onIconHover' => true,
    ]
])->hint('Enter <b>valid notes</b> to identify this record.');

## Expected behavior and actual behavior

When I follow those steps, I see...
I see the icon but it not works. It wont show the hint

I was expecting...
that when I 
enable onIconClick/onIconHover and 
disable onLabelClick+onLabelHover, 
i can see the hint icon and the hint when i hover or click the icon.

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-widget-activeform version: 1.4.8 and dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/active-form)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-widget-activeform without other plugins.

**Comment by vadim-bulochnik** [comment]
The same problem for me.
