### ISSUE TITLE
ActiveField::getToggleFieldList() calls same code twice

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-widget-activeform#89]
Line [1444](https://github.com/kartik-v/yii2-widget-activeform/blob/6980832716b7075c103999c0574699b26e263f6c/ActiveField.php#L1444):

    if ($asButtonGroup && $checked) {
        Html::addCssClass($labelOptions, 'active');
    }

Line [1455](https://github.com/kartik-v/yii2-widget-activeform/blob/6980832716b7075c103999c0574699b26e263f6c/ActiveField.php#L1455):

    if ($checked && $asButtonGroup) {
        Html::addCssClass($labelOptions, 'active');
    }

I don't see any particular reason for this, so I assume it's just some reminiscent code.

**Comment by Enrica-r** [comment]
I think so also. I can't see any reason. The second part could be removed but it's not urgent.

**Comment by kartik-v** [comment]
Thanks for the suggestion. Code will be updated.
