### ISSUE TITLE
Lastest update breaks FieldRange widget.

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-widget-activeform#92]
I just updated to the latest version and now my FieldRange widgets are broken.  Below is the error:

Undefined index: labelSpan

1. in /Users/maz/projects/gsys/vendor/kartik-v/yii2-widget-activeform/ActiveForm.php at line 190
181182183184185186187188189190191192193194195196197198199                      

```   /**
     * Gets form layout style configuration. This method is used by [[\kartik\field\FieldRange]] widget.
     *
     * @return array the form layout style configuration.
     */
    public function getFormLayoutStyle()
    {
        $config = $this->formConfig;
        $span = $config['labelSpan'];  /* line 190 */
        $size = $config['deviceSize'];
        $labelCss = $inputCss = $offsetCss = ActiveField::NOT_SET;
        $iSpan = intval($span);
        if ($span != ActiveField::NOT_SET && $iSpan > 0) {
            // validate if invalid `labelSpan` is passed else set to [[DEFAULT_LABEL_SPAN]]
            if ($iSpan <= 0 && $iSpan >= $this->fullSpan) {
                $iSpan = self::DEFAULT_LABEL_SPAN;
            }
```

**Comment by kartik-v** [comment]
This has been resolved via #91.

**Comment by maz0717** [comment]
I  just found that when I was going to do a pull request.  Has that been merged yet?  I fixed it slightly differently.  Instead of null I used ActiveField::NOT_SET because that is what you were comparing against further down.

**Comment by maz0717** [comment]
$span = isset($config['labelSpan']) ? $config['labelSpan']                          : ActiveField::NOT_SET;                                             
        $size = isset($config['deviceSize']) ? $config['deviceSize']            
            : ActiveField::NOT_SET;
