### ISSUE TITLE
Undefined index: labelSpan

### ISSUE THREAD

**Issue by hdewaart** [kartik-v/yii2-widget-activeform#93]
#29  Updating ezyang/htmlpurifier (v4.9.3 => v4.10.0): Loading from cache
  - Updating yiisoft/yii2 (2.0.13.1 => 2.0.14.2): Loading from cache
  - Updating yiisoft/yii2-bootstrap (2.0.7 => 2.0.8): Loading from cache
  - Updating phpseclib/phpseclib (2.0.9 => 2.0.10): Loading from cache
  - Updating yiisoft/yii2-faker (2.0.3 => 2.0.4): Loading from cache
  - Updating tinymce/tinymce (4.7.6 => 4.7.9): Loading from cache
  - Updating kartik-v/yii2-widget-activeform (v1.4.8 => v1.4.9): Loading from cache
  - Updating kartik-v/yii2-icons dev-master (84a1da9 => 46dd672):  Checking out 46dd67204e
  - Updating kartik-v/yii2-widget-select2 dev-master (d46c74c => d08a5b3):  Checking out d08a5b302f

After updating I get this

PHP Notice 'yii\base\ErrorException' with message 'Undefined index: labelSpan' 
in /var/www/html/planning/vendor/kartik-v/yii2-widget-activeform/ActiveForm.php:190

```
use kartik\widgets\ActiveForm;

$form = ActiveForm::begin([
    'id' => $model->formName().'-form',
    'type' => 'horizontal',
    'enableClientValidation' => true,
    'formConfig' => ['deviceSize' => 0],
]);
```

**Comment by kartik-v** [comment]
Duplicate to #91 and #92... get the latest code.
