### ISSUE TITLE
Trait 'kartik\base\BootstrapTrait' not found

### ISSUE THREAD

**Issue by lowap** [kartik-v/yii2-widget-activeform#96]
Hi,

sorry I don't have enough time now for all the details, just a quick and dirty way to say: I've upgraded now many modules and since then I get the following error message when opening a view generated with giiant (so it's kinda "default" view file): 

    Trait 'kartik\base\BootstrapTrait' not found

    in ...\vendor\kartik-v\yii2-widget-activeform\src\ActiveForm.php

I've no clue what has it to do with ActiveForm Widget. Can you please check this for me? Thanks a lot!

**Comment by nikolaykovenko** [comment]
I have the same problem. The issue is in activeform dependency: current master of kartik-v/yii2-widget-activeform requires "kartik-v/yii2-krajee-base": "~1.7" but BootstrapTrait was added in new version of kartik-v/yii2-krajee-base.
And if composer can't install new version of kartik-v/yii2-krajee-base because of some version conflicts or restrictions, it installs old version 1.7 and brakes the activeform component.

**Comment by mice-tm** [comment]
Just the same after

**Comment by kartik-v** [comment]
You would need to check your composer dependencies for your app and get the latest release of yii2-krajee-base which is v1.9.x. 

Remove all unnecessary dependencies to other extensions - for example if you are installing yii2-widget-activeform - it will automatically install yii2-bootstrap and yii2-bootstrap4 - remove these from your composer dependencies.

@nikolaykovenko  - ~1.7 means v1.7 to v2.0 - if you are getting the old version installed - check your app's composer.json and remove all other hardcoded old versions of other extensions like `yii2-bootstrap`.

**Comment by lowap** [comment]
Until now I have never touched my apps composer.json file. So if something is in there, it was added automatically by installing an extensions or something. I have `yii2-widget-activeform: @dev` already in my composer. That means it should be able already to automatically update `yii2-krajee-base`, shouldn't it?
I have no extensions duplicated. What should I remove now...?

    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.5",
        "yiisoft/yii2-bootstrap": "^2.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "mdmsoft/yii2-admin": "~2.0",
        "dektrium/yii2-user": "^0.9.12",
        "bedezign/yii2-audit": "1.0.8",
        "machour/yii2-notifications": "@dev",
        "schmunk42/yii2-giiant": "@stable",
        "yiisoft/yii2-jui": "^2.0",
        "kartik-v/yii2-detail-view": "*",
        "kartik-v/yii2-widget-activeform": "@dev",
        "yiisoft/yii2-imagine": "^2.1",
        "kartik-v/yii2-grid": "@dev",
        "kartik-v/yii2-tree-manager": "@dev",
        "kartik-v/yii2-editable": "*",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-datecontrol": "^1.9",
        "thiagotalma/yii2-fullcalendar": "*",
        "philippfrenzel/yii2fullcalendar": "*",
        "chrisb34/yii2-report-grid": "@dev",
        "kartik-v/yii2-widget-switchinput": "*",
        "kartik-v/yii2-mpdf": "dev-master"
    },

**Comment by lowap** [comment]
I have done it now like you suggested:

    - Removing yiisoft/yii2-imagine (2.1.1)
    - Removing imagine/imagine (v0.7.1)
    - Removing kartik-v/yii2-detail-view (v1.7.6)
    - Installing kartik-v/yii2-detail-view (dev-master 3764c01): Downloading (100%)
    - Removing kartik-v/yii2-editable (v1.7.6)
    - Installing kartik-v/yii2-editable (dev-master 4a41119): Downloading (100%)
    - Removing kartik-v/yii2-widgets (v3.4.0)
    - Installing kartik-v/yii2-widgets (dev-master 24d3a39): Downloading (100%)
    - Removing kartik-v/yii2-datecontrol (v1.9.6)
    - Installing kartik-v/yii2-datecontrol (dev-master b22dc0b): Downloading (100%)

still no sign of updating `yii2-krajee-base`...?

**Comment by lowap** [comment]
Btw, how can I know which are duplicates? It should be somehow easily noticeable, shouldn't it?

**Comment by kartik-v** [comment]
Yes - it is not that difficult - look into every new extension's composer.json before you install them to understand the dependency.

**Comment by kartik-v** [comment]
Yes - it is not that difficult - look into every new extension's composer.json before you install them to understand the dependency.

I assume you should have the latest version of `yii2-krajee-base` - if not you may [try going through this webtip for composer failing to update packages](http://webtips.krajee.com/composer-fails-update-vendor-packages/)

**Comment by lowap** [comment]
Maybe it has not updated `yii2-krajee-base` but my app is working now, and that's the point! Many thanks for your help!

**Comment by lowap** [comment]
I've done according to your webtip, and it's installing now `yii2-krajee-base 1.8.9` again...?

**Comment by lowap** [comment]
You have changed something, right? Now it takes the newest version.

**Comment by kartik-v** [comment]
Not sure - try updating packages via `composer update` again - the latest release of `yii2-krajee-base` is now `v1.9.1`

**Comment by lowap** [comment]
v1.9.1 perfect! Many thanks!
