### ISSUE TITLE
Unable to install a stable version

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-widget-activeform#97]
All of the repo's are a mess right now.  There is no way to install a "stable" set of kartik modules.  In this repo 1.4.9 is marked stable, but it contains undefined indexes.  dev-master now causes issues because of the addition of bootstrap4 so "use the latest code" no longer solved the undefined index issue.  The addition of bootstrap4 is causing a whole new set of issues.  I can't even use dev master because of bootstrap conflicts.    yii's bootstrap and bootstrap4 modules cannot be included at the same time because they will try to install both the 3.x and 4.x version of bootstrap.

Bootstrap 4 either needs to be an optional requirement or repo's need to be bumped a major version for bootstrap4.  We need some way to get the latest fixes without having to install bootstrap4.  I would also recommend marking 87a35a829f5842f0ff88113e90e24489e9c57abf as stable 1.5.0.

For anyone else coming across this issue, force version 1.4.8 in your composer.json file for now.

**Comment by kartik-v** [comment]
Latest stable version is v1.5.0. Refer [the comment](https://github.com/kartik-v/yii2-widget-activeform/issues/96#issuecomment-413422618).

You may need to check your composer config for any forced version settings you may have done for dependent extensions for `yii2-widget-activeform` - i.e. `yii2-krajee-base`, `yii2-bootstrap`, or `yii2-bootstrap4` - if you just want the latest release of `yii2-widget-activeform` - just remove these extensions from your composer and set `yii2-widget-activeform: @dev` in composer require section for everything else to automatically get installed.

If you need an older release of those extensions then do a forced downgrade by setting the right versions.

**Comment by kartik-v** [comment]
@maz0717 can you paste your composer.json require section - let me see if I can guide you.

**Comment by kartik-v** [comment]
@maz0717 can you paste your composer.json require section - let me see if I can guide you. There definitely seems an issue of conflicting dependencies that you have set in your composer.json.

**Comment by maz0717** [comment]
```
    "require": {
        "php": ">=7.2.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-jui": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.1.0",
        "yiisoft/yii2-sphinx": "dev-master",
        "yiisoft/yii2-imagine": "~2.1.0",
        "yiisoft/yii2-twig": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "^2.1",
        "creocoder/yii2-nested-sets": "dev-custom as 0.9.x-dev",
        "kartik-v/yii2-tree-manager": "*",
        "kartik-v/yii2-krajee-base": "*",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-widget-fileinput" : "*",
        "kartik-v/yii2-widget-depdrop" : "*",
        "kartik-v/yii2-builder": "*",
        "kartik-v/yii2-field-range": "*",
        "kartik-v/yii2-detail-view": "*",
        "kartik-v/yii2-mpdf": "*",
        "kartik-v/yii2-datecontrol": "*",
        "kartik-v/yii2-dynagrid": "*",
        "kartik-v/yii2-sortable": "@dev",
        "kartik-v/yii2-grid": "*",
        "kartik-v/yii2-widget-activeform": "1.4.8",
        "2amigos/yii2-ckeditor-widget" : "~2.1",
        "2amigos/yii2-highcharts-widget" : "*",
        "2amigos/yii2-gallery-widget": "~1.0",
        "vova07/yii2-console-runner-extension" : "*",
        "maz0717/yii2-phpexcel": "dev-master",
        "yii2mod/yii2-validators": "*",
        "npm-asset/barba.js": "*",
        "npm-asset/modernizr": "*",
        "bower-asset/masonry": "*",
        "bower-asset/flickity": "*",
        "bower-asset/noty": "*",
        "bower-asset/openseadragon": "*",
        "bower-asset/eonasdan-bootstrap-datetimepicker": "*",
        "google/apiclient": "^2.0",
        "himiklab/yii2-recaptcha-widget" : "*",
        "geoip2/geoip2": "~2.0",
        "paulzi/yii2-json-behavior": "^1.0",
        "brussens/yii2-maintenance-mode": "*",
        "tijsverkoyen/css-to-inline-styles": "^2.2",
        "rambomst/php-bounce-handler": "^1.3",
        "crazy-max/cws-mail-bounce-handler": "*",
        "janisto/yii2-timepicker": "*",
        "trntv/yii2-datetime-widget": "dev-master",
        "bower-asset/bootstrap-daterangepicker": "*",
        "tinymce/tinymce": "*",
        "softark/yii2-dual-listbox": "dev-master",
        "bower-asset/bootstrap-datepicker": "*",
        "bower-asset/selectize": "*",
        "taxjar/taxjar-php": "^1.7",
        "vinceg/usps-php-api": "^1.0",
        "paypal/rest-api-sdk-php": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",
        "bazilio/yii2-stubs-generator": "^1.2"
    },
```

**Comment by kartik-v** [comment]
Here you go - try to use this updated composer.json require section - where I have removed redundant duplicate dependencies for kartik-v widgets:

```
    "require": {
        "php": ">=7.2.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-jui": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.1.0",
        "yiisoft/yii2-sphinx": "dev-master",
        "yiisoft/yii2-imagine": "~2.1.0",
        "yiisoft/yii2-twig": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "^2.1",
        "creocoder/yii2-nested-sets": "dev-custom as 0.9.x-dev",
        "kartik-v/yii2-widgets": "@dev",
        "kartik-v/yii2-tree-manager": "@dev",
        "kartik-v/yii2-builder": "@dev",
        "kartik-v/yii2-field-range": "@dev",
        "kartik-v/yii2-detail-view": "@dev",
        "kartik-v/yii2-mpdf": "@dev",
        "kartik-v/yii2-datecontrol": "@dev",
        "kartik-v/yii2-dynagrid": "@dev",
        "2amigos/yii2-ckeditor-widget" : "~2.1",
        "2amigos/yii2-highcharts-widget" : "*",
        "2amigos/yii2-gallery-widget": "~1.0",
        "vova07/yii2-console-runner-extension" : "*",
        "maz0717/yii2-phpexcel": "dev-master",
        "yii2mod/yii2-validators": "*",
        "npm-asset/barba.js": "*",
        "npm-asset/modernizr": "*",
        "bower-asset/masonry": "*",
        "bower-asset/flickity": "*",
        "bower-asset/noty": "*",
        "bower-asset/openseadragon": "*",
        "bower-asset/eonasdan-bootstrap-datetimepicker": "*",
        "google/apiclient": "^2.0",
        "himiklab/yii2-recaptcha-widget" : "*",
        "geoip2/geoip2": "~2.0",
        "paulzi/yii2-json-behavior": "^1.0",
        "brussens/yii2-maintenance-mode": "*",
        "tijsverkoyen/css-to-inline-styles": "^2.2",
        "rambomst/php-bounce-handler": "^1.3",
        "crazy-max/cws-mail-bounce-handler": "*",
        "janisto/yii2-timepicker": "*",
        "trntv/yii2-datetime-widget": "dev-master",
        "bower-asset/bootstrap-daterangepicker": "*",
        "tinymce/tinymce": "*",
        "softark/yii2-dual-listbox": "dev-master",
        "bower-asset/bootstrap-datepicker": "*",
        "bower-asset/selectize": "*",
        "taxjar/taxjar-php": "^1.7",
        "vinceg/usps-php-api": "^1.0",
        "paypal/rest-api-sdk-php": "*"
    },
```

**Comment by kartik-v** [comment]
Since `yii2-bootstrap4` is not yet stable - I will try to release an interim version of `yii2-krajee-base` without `yii2-bootstrap4` dependency.

**Comment by maz0717** [comment]
Finished: success: 6, skipped: 0, failure: 0, total: 6
Package operations: 0 installs, 9 updates, 0 removals
  - Updating kartik-v/yii2-widget-activeform (v1.4.8 => v1.4.9):  Checking out 578de8c5dd
  - Removing kartik-v/yii2-widgets (v3.4.0)
  - Installing kartik-v/yii2-widgets (dev-master 24d3a39): Cloning 24d3a3942a from cache
  - Removing kartik-v/yii2-builder (v1.6.3)
  - Installing kartik-v/yii2-builder (dev-master fc4f86c): Cloning fc4f86cec4 from cache
  - Removing kartik-v/yii2-field-range (v1.3.2)
  - Installing kartik-v/yii2-field-range (dev-master dccc408): Cloning dccc40867f from cache
  - Removing kartik-v/yii2-detail-view (v1.7.6)
  - Installing kartik-v/yii2-detail-view (dev-master 3764c01): Cloning 3764c01950 from cache
  - Removing kartik-v/yii2-mpdf (v1.0.2)
  - Installing kartik-v/yii2-mpdf (dev-master 67980ab): Cloning 67980ab786 from cache
  - Updating kartik-v/yii2-datecontrol (v1.9.6 => dev-master b22dc0b):  Checking out b22dc0b87c
  - Updating kartik-v/yii2-sortable (dev-master 83784e4 => v1.2.0):  Checking out 650dfd6876
  - Updating kartik-v/yii2-dynagrid (v1.4.8 => dev-master 8a6c7a2):  Checking out 8a6c7a243e

Notice that it updated widget to 1.4.9.  Which gives me the following error when using it:
Undefined index: labelSpan
1. in /Users/maz/projects/gsys/vendor/kartik-v/yii2-widget-activeform/ActiveForm.php

That error was fixed in 1.5.0, but if I force 1.5.0-dev, It wants base 1.9.0, which in turn wants yii2-bootstrap4.  Which in turn conflicts with yii2-bootstrap, which is required for yii2-adminlte-asset.

**Comment by maz0717** [comment]
yii2-krajee-base not requiring bootstrap 4 would probably solve many peoples problems.  And would solve this issue.

**Comment by maz0717** [comment]
You can't include yii2-bootstrap and yii2-bootstrap4 in the same project.  One wants bower-asset/bootstrap[v3.x] and the other wants bower-asset/bootstrap[v4.x]

    - Can only install one of: bower-asset/bootstrap[v3.3.6, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.4, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.2, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.1, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.3.0, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.2.0, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.1.1, v4.1.0].
    - Can only install one of: bower-asset/bootstrap[v3.1.0, v4.1.0].

**Comment by kartik-v** [comment]
Yes - I have removed the dependency to yii2-bootstrap4 currently (refer kartik-v/yii2-krajee-base#92).

However developers can choose what they want by setting `bsVersion` in the widgets to `3.x` or `4.x` and for `4.x` manually install `yii2-bootstrap4` - else widget will throw exception.

There is not going to be two separate extensions in `kartik-v` extensions - its just through the `bsVersion` property.

**Comment by maz0717** [comment]
That's great.  Thank you so much.  As always, you have been very helpful.
